---
name: Stack Healthcheck
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy the stack
        run: timeout 120 docker-compose up -d

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3