---
name: Stack Healthcheck
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy the stack
        run: docker-compose up -d

      - name: Test PGAdmin
        run: docker run --network container:resolve_pgadmin appropriate/curl -s --retry 10 --retry-connrefused http://localhost/

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true